### ISSUE TITLE
Group resource failing on Nano server.

### ISSUE THREAD

**Issue by AndreasSobczyk** [PowerShell/PSDscResources#38] opened 2017-02-17 09:21 UTC
I am trying to use the Group resource to manage members of the administrators group on nano server but getting an error on Test-TargetResource. The same configuration works fine on a GUI server.

It seems to be line 85 and 89 in the function Test-TargetResourceOnNanoServer that is failing if $groupMembers is only containing one Local user member. This could be because Get-MembersOnNanoServer is returning a string instead of a array. It is working i typecast the variable $groupMembers to array the .Count is working 

Also the Function Get-MembersOnNanoServer is only returning local members and not including domain members. What is the reason for that? 
As i see it the function will then never verify that domain users is added to the group and always add them.

#--- ERROR ---#
PowerShell DSC resource MSFT_GroupResource  failed to execute Test-TargetResource functionality with error message: The property 'Count' cannot be found on this object. Verify that the property exists. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 #--- ERROR ---#

**Comment by kwirkykat** [comment] 2017-02-17 20:49
Group only supports local members on Nano server.

This is not a bug with the type that Get-MembersOnNanoServer is returning.
Get-MembersOnNanoServer returns a string array, not a string, but because PowerShell hates arrays (grrrr) the function only returns a single string if it returns an array with a single string in it.

The simplest fix is just to wrap any calls to Get-MembersOnNanoServer in an array like this:
`$members: @( Get-MembersOnNanoServer -Group $group )`

I believe there is also some way to always return an arrya from Get-MembersOnNanoServer by adding a single comma after the return statement.

**Comment by kwirkykat** [comment] 2017-02-22 19:13
Fixed by #39

**Closed by kwirkykat** 2017-02-22 19:13 UTC
Labels: bug, in progress
