### ISSUE TITLE
Can't import a specific resource

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/PSDscResources#47] opened 2017-03-14 15:58 UTC
I am finding this module challenging to use since there are naming conflicts with PSDesiredStateconfiguration. But for now I am trying to use this in a DSC Configuration

```
Import-DscResource -ModuleName "PSDscResources" -ModuleVersion "2.5.0.0" -Name "User"
```
But both the ISE and VSCode give me an error that the resource can't be found. I know the syntax is correct because this line parses correctly.

```
Import-DscResource -ModuleName "xTimeZone" -ModuleVersion "1.6.0.0" -name "xtimezone"
```

**Comment by kwirkykat** [comment] 2017-03-14 17:05
@jdhitsolutions What is your full PowerShell/WMF version?

**Comment by jdhitsolutions** [comment] 2017-03-14 17:09
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.15055.0                                                                             
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.15055.0                                                                            
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

**Comment by jdhitsolutions** [comment] 2017-03-14 17:12
I still think there is something funky with DSC and PSDscResources and PSDesiredStateconfiguration. If I try to use this in a config:
```
Import-DSCresource -ModuleName PSDesiredStateConfiguration -name User
Import-DscResource -ModuleName
@{ModuleName="xPSDesiredStateConfiguration";ModuleVersion="5.0.0.0"},
   @{ModuleName="xComputerManagement";ModuleVersion="1.8.0.0"},
   @{ModuleName="xNetworking";ModuleVersion="3.0.0.0"},
   @{ModuleName='xWindowsUpdate';ModuleVersion = '2.5.0.0'}
```
I still get this error:
```
ImportClassResourcesFromModule : Exception calling
"ImportClassResourcesFromModule" with "3" argument(s): "Resource
name 'WindowsPackageCab' is already being used by another Resource or
Configuration."
```
Even running the config in new PowerShell session with no profiles.

**Comment by kwirkykat** [comment] 2017-03-14 17:58
So you aren't importing PSDscResources in your config and this error is still showing up?

This is similar to #43

**Comment by jdhitsolutions** [comment] 2017-03-14 18:15
I get errors whether I import it or not. I have tried numerous combinations and the only thing that works is to uninstall PSDscResources.  It looks like xPSDesiredStateConfiguration is automatically imported whether you specify it or not and I wonder if that is trying to automatically load something else. 

So I see two symptoms here and they may be related. 1 - You can't import a resource by name. 2 - PowerShell reports resource name conflicts between this module and PSDesiredStateConfiguration.

**Comment by kwirkykat** [comment] 2017-03-14 19:36
Does importing

**Comment by jdhitsolutions** [comment] 2017-03-14 19:40
Fine -- if you want to close this but even after looking at #43 I don't think you've really addressed this issue. I'll come up with a set of steps to repro and and re-post an issue.

**Comment by kwirkykat** [comment] 2017-03-14 19:46
Sorry didn't mean to do that

**Comment by kwirkykat** [comment] 2017-03-14 19:49
Does importing PSDscResources by itself even work?
This looks like a newer WMF version than I have on my test machines.
So I'm thinking this must be a regression of a previous bug that we fixed in the DSC engine that did not allow overwriting of in-box resources.
I'm looking into it

**Comment by kwirkykat** [comment] 2017-03-14 20:03
@jdhitsolutions Where is your version of WMF coming from?

I am using 5.1.14409.1005 (the newest version I know of that you can download [here](https://www.microsoft.com/en-us/download/details.aspx?id=54616)) and I can also confirm that it works on 5.1.14393.693 which I have on a test box.

Since your version is 5.1.15055.0 I would expect it to be newer than the versions I have. However, the version of WMF 5.1 that went out as the 'WMF 5.1 Preview' was something like 5.1.14394.0 which *looks* newer than 5.1.14393.693 but was actually from a different branch of code that didn't have the right DSC engine bug fix yet so it was actually older code.

**Comment by kwirkykat** [comment] 2017-03-14 20:12
@jdhitsolutions Are you on Windows Server 2016/Windows 10?

**Comment by kwirkykat** [comment] 2017-03-14 20:59
@jdhitsolutions Is this WMF from an Insider build?

**Comment by kwirkykat** [comment] 2017-03-14 21:07
@jdhitsolutions Aha! This is the [latest Windows Insider build](https://blogs.windows.com/windowsexperience/2017/03/10/announcing-windows-10-insider-preview-build-15055-pc-mobile/#hsVxhruQUEDW0xXl.97) that was released last week. I have opened this bug with DSC. I am marking this bug as external for now since there is nothing I can do in this repository/module to fix this.

**Comment by jdhitsolutions** [comment] 2017-03-14 22:36
Ok. I'll try to test with another Win10 client that isn't on the Insider Build ring or 5.1 on Windows 8.1

**Comment by jdhitsolutions** [comment] 2017-03-15 13:59
I guess life in the fast lane has its ups and downs. Got a new build last night and re-running the same configs now works as expected without any of the errors I reported.
```

**Closed** 2017-03-24 23:14 UTC
Labels: bug, external, in progress
